CREATE TABLE "temas" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar(80) UNIQUE NOT NULL,
  "icone" varchar(10)
);

CREATE TABLE "dificuldades" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar(20) UNIQUE NOT NULL
);

CREATE TABLE "palavras" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "palavra" varchar(100) UNIQUE NOT NULL,
  "tema_id" int NOT NULL,
  "dificuldade_id" int NOT NULL,
  "criado_em" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "jogadores" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar(100) NOT NULL,
  "email" varchar(150) UNIQUE,
  "criado_em" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "partidas" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "jogador_id" int NOT NULL,
  "palavra_id" int NOT NULL,
  "erros" tinyint NOT NULL DEFAULT 0,
  "venceu" boolean NOT NULL DEFAULT false,
  "jogado_em" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

COMMENT ON TABLE "temas" IS 'Temas disponíveis para categorizar as palavras';

COMMENT ON COLUMN "temas"."id" IS 'Chave primária';

COMMENT ON COLUMN "temas"."nome" IS 'Ex: Natureza, Tecnologia';

COMMENT ON COLUMN "temas"."icone" IS 'Emoji representativo do tema';

COMMENT ON TABLE "dificuldades" IS 'Níveis de dificuldade das palavras';

COMMENT ON COLUMN "dificuldades"."nome" IS 'Facil | Medio | Dificil';

COMMENT ON TABLE "palavras" IS 'Palavras usadas no jogo da forca';

COMMENT ON COLUMN "palavras"."id" IS 'Chave primária';

COMMENT ON COLUMN "palavras"."palavra" IS 'Sempre em maiúsculo';

COMMENT ON TABLE "jogadores" IS 'Jogadores registrados no sistema';

COMMENT ON COLUMN "jogadores"."email" IS 'Opcional — para ranking futuro';

COMMENT ON TABLE "partidas" IS 'Histórico de partidas — relacionamento N:N entre Jogador e Palavra';

COMMENT ON COLUMN "partidas"."erros" IS 'Máximo 6 erros';

ALTER TABLE "palavras" ADD FOREIGN KEY ("tema_id") REFERENCES "temas" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "palavras" ADD FOREIGN KEY ("dificuldade_id") REFERENCES "dificuldades" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "partidas" ADD FOREIGN KEY ("jogador_id") REFERENCES "jogadores" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "partidas" ADD FOREIGN KEY ("palavra_id") REFERENCES "palavras" ("id") DEFERRABLE INITIALLY IMMEDIATE;
